"""
Generate an editable run-config YAML from the *live* code defaults.

The point of this module is that the template is never hand-maintained: every
value is read from `Config` / `QCThresholds` model fields (and a couple of
function-signature defaults) at generation time, so an emitted config always
matches the current function defaults even after someone edits them. The prose
comments are curated here; only the values are injected.

`chromcov gen-config -o my.yaml` writes it; the layout mirrors what
`Config.from_yaml` reads back (see config.py), so the file round-trips.

TODO (data-driven generator): the template below is still hand-structured -- the
section grouping, per-field comments, and the `_QC_COMMENTS` list are maintained
here by hand, so adding a Config field means editing both this file and
`_YAML_TO_FIELD` in config.py. Plan: give each param a single documentation entry
(e.g. a `PARAM_DOCS: dict[field_name -> help text]`, ideally colocated with the
model/`_YAML_TO_FIELD` so config.py owns the field->section->doc mapping in one
place), then rebuild this generator to walk that mapping + the live model defaults
instead of a literal template. One source for both the YAML comments and any other
docs (CLI `--help`, README table). Values already stay in sync; this closes the
remaining structure/prose duplication so a new field shows up everywhere for free.
"""
from __future__ import annotations

from pathlib import Path

from .config import Config, QCThresholds, SAM_FLAGS


def _config_defaults() -> dict:
    """Resolved default value per Config field (calls default_factory; required
    fields -> None so they render as commented placeholders)."""
    out: dict = {}
    for name, fi in Config.model_fields.items():
        if fi.is_required():
            out[name] = None
        elif fi.default_factory is not None:
            out[name] = fi.default_factory()  # type: ignore[call-arg]
        else:
            out[name] = fi.default
    return out


def _flag_names(mask: int) -> list[str]:
    """Bitmask -> the SAM flag names that compose it (config-friendly form)."""
    return [name for name, bit in SAM_FLAGS.items() if mask & bit]


def _inline(seq) -> str:
    """A sequence as an inline YAML list, quoting strings, bare ints."""
    parts = [f'"{x}"' if isinstance(x, str) else str(x) for x in seq]
    return "[" + ", ".join(parts) + "]"


def _bool(v) -> str:
    return "true" if v else "false"


def _flag_block(key: str, mask: int, comment_block: str = "") -> str:
    """A -f/-F/-G flags entry: inline `[]` when empty, else a YAML block list."""
    names = _flag_names(mask)
    if not names:
        return f"{key}: []"
    lines = [comment_block] if comment_block else []
    lines.append(f"{key}:")
    lines += [f"    - {n}" for n in names]
    return "\n".join(lines)


# QC threshold key -> its inline comment (values come from the model at runtime).
_QC_COMMENTS = [
    ("gain_cn", "CN >= this (autosomes) -> CN_GAIN"),
    ("loss_cn", "CN <= this (autosomes) -> CN_LOSS"),
    ("depleted_cn", "CN <= this (any contig) -> CN_DEPLETED"),
    ("min_median", "median depth < this -> LOW_DEPTH"),
    ("uneven_robust_cv", "MAD/median > this -> UNEVEN"),
    ("min_breadth_20x", "breadth@20x < this -> LOW_CALLABLE"),
    ("extreme_median_mult", "median > this * baseline -> EXTREME_DEPTH"),
]


def render_default_config() -> str:
    """Build the commented config text from the live model defaults."""
    d = _config_defaults()
    qc = QCThresholds().model_dump()

    exclude_comment = (
        "  # -F: exclude a read if it has ANY of these flags.\n"
        "  # NOTE: `duplicate` is deliberately NOT excluded by default -- in high-depth\n"
        "  # cancer data, coordinate collisions make duplicate-marking drop real coverage.\n"
        "  # Add `- duplicate` here to reproduce a standard dedup'd number."
    )
    exclude_flags = _flag_block("  exclude_flags", d["exclude_flags"], exclude_comment)
    include_flags = _flag_block("  include_flags", d["include_flags"])
    exclude_all = _flag_block("  exclude_all_flags", d["exclude_all_flags"])

    qc_lines = "\n".join(
        f"  {k}: {str(qc[k]):<8}# {c}" for k, c in _QC_COMMENTS
    )

    return f"""\
# chromcov run configuration -- every option with its current default value.
#
# GENERATED by `chromcov gen-config` from the live Config model defaults, so it
# always matches the code. Copy/rename freely, uncomment `inputs.cram` and
# `inputs.reference`, and edit what you need. CLI flags override anything here.

# --- inputs ------------------------------------------------------------------
# cram + reference are required (no default). Provide them here or on the CLI.
inputs:
  # cram: path/to/sample.cram         # REQUIRED -- the CRAM to measure
  # reference: path/to/genome.fa      # REQUIRED -- FASTA the CRAM was compressed against
  index: null                         # CRAM index; null -> <cram>.crai
  verify_reference: {d["verify_reference"]}          # reference-M5 preflight check: auto | full | skip

# --- read filtering (samtools flag/MAPQ semantics) ---------------------------
filters:
  # -Q: minimum mapping quality a read must have
  min_mapping_quality: {d["min_mapping_quality"]}

  # -f: require that a read has ALL of these flags
{include_flags}

{exclude_flags}

  # -G: exclude a read ONLY if it has ALL of these flags
{exclude_all}

# Valid flag names: {", ".join(SAM_FLAGS)}.
# Integer bitmasks are also accepted.

# --- contig selection --------------------------------------------------------
# Glob patterns over reference names. include first, then exclude. Keeps the
# decoy/unplaced artifact contigs out of the headline report.
contigs:
  # chroms: [chr1, chr2]              # explicit subset; overrides include/exclude (default: all)
  include: {_inline(d["include_contigs"])}
  exclude: {_inline(d["exclude_contigs"])}
  # chrM is kept by default but flagged in reports because of high depth

# --- analysis (used only with --full) ----------------------------------------
analysis:
  window: {d["window"]}              # windowed-mean bin size (bp)
  hist_cap: {d["hist_cap"]}           # clip extreme pileup depths into a top bin
  breadth_thresholds: {_inline(d["breadth_thresholds"])}   # depth cutoffs for breadth-of-coverage

# --- copy number (used only with --full) -------------------------------------
copy_number:
  ploidy: {d["ploidy"]}
  baseline: {d["baseline"]}   # easy-autosomal-median | autosomal-median
  # 'easy-autosomal-median' uses the callability strata below -> repeat pileups
  # don't inflate the CN=2 reference. Falls back to all autosomes if no strata.
  scatter_cap_cn: {d["scatter_cap_cn"]:g}                  # cap on approx copy number on the scatter y-axis

# --- QC abnormality-flag thresholds ------------------------------------------
# Tune when a chromosome/window is flagged. Set any subset; unset keys default.
qc:
{qc_lines}

# --- callability strata (Park Lab SMaHT_Regional_Categorization, GRCh38) ------
# label -> BED[.gz] path. Empty by default (no stratification). Fetch the SMaHT
# BEDs with `chromcov fetch strata`, then either fill these in or use --strata.
strata: {{}}
  # easy: data/SMaHT_easy_hg38.bed.gz
  # difficult: data/SMaHT_difficult_hg38.bed.gz
  # extreme: data/SMaHT_extreme_hg38.bed.gz
  # scatter_min_easy_frac: {d["scatter_min_easy_frac"]}   # >0 drops windows mostly outside 'easy' from the scatter

# --- output ------------------------------------------------------------------
# `--full` writes per-base bedgraphs + the combined table + plots; the default
# (no --full) prints just the mean-only per-chromosome table.
output:
  outdir: {d["outdir"]}
  plots: {_bool(d["plots"])}

# -----------------------------------------------------------------------------
# NOT configurable via this file (code constants), listed so the reference is
# complete. Config.from_yaml has no key for these.
#
#   plot styling          figure sizes, dpi, per-tier colors (plots.py).
#   fetch source          SMaHT BED base URL + filenames (fetch.py).
#
# There is deliberately NO per-base max-depth cap: unlike pileup/count_coverage
# tools, calc_cov.py tallies read get_blocks() into a finite-difference array, so
# per-base depth is exact and unbounded. `analysis.hist_cap` only clips the
# histogram's top bin (for genome-wide pooling); it never affects reported means.
"""


def write_default_config(path: str | Path) -> Path:
    """Render the live-default config and write it to `path`."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_default_config())
    return path
